library(foreign)
library(dplyr)    
statadata <- read.dta("C:/Users/SALEM/Downloads/37276-0001-Data.dta")
View(statadata)
library(tidyverse)
statadata2 <- select(statadata, ARG:SEX, FIRARM_C, TRANSP_C, CLASS_C, YEAR:CMTX2)
View(statadata2)
ggplot(data = statadata2) + geom_bar(mapping = aes(x = SEX, fill = SEX ))
statadata3 <- filter(statadata2, SEX == "Male", DISP == "Treated/released") 
View(statadata3)
statadata4 <- filter(statadata2, SEX == "Male", DISP == "Treated/released", FIRARM_C == "Rifle")
View(statadata4)
statadata5 <- filter(statadata2, SEX == "Male", DISP == "Treated/released", FIRARM_C == "Handgun")
View(statadata5)
statadata6 <- select(statadata, ARG:SEX, FIRARM_C, LOC_C, MSTAT_C, TRANSP_C, CLASS_C, AGENYR_C,WHO_C, AGENG_C,RACE_C,HISP_C, YEAR)
View(statadata6)
statadata2 %>% count(SEX)
statadata4 %>% count(FIRARM_C)
statadata5 %>% count(FIRARM_C)
ggplot(data = statadata) + stat_count(mapping = aes(x = FIRARM_C))
ggplot(data = statadata) + stat_count(mapping = aes(x = BDYPT))
ggplot(data = statadata6) + geom_bar(mapping = aes(x = FIRARM_C, fill = SEX))
ggplot(data = statadata6) + geom_bar(mapping = aes(x = FIRARM_C, fill = ONTHEJOB))
ggplot(data = statadata6) + geom_bar(mapping = aes(x = FIRARM_C, fill = AGENG_C))
ggplot(data = statadata6) + geom_bar(mapping = aes(x = FIRARM_C, fill = AGENYR_C))
ggplot(data = statadata6) + geom_bar(mapping = aes(x = FIRARM_C, fill = SEX), position = "dodge")
ggplot(data = statadata6) + geom_bar(mapping = aes(x = FIRARM_C, fill = ONTHEJOB), position = "dodge")
ggplot(data = statadata6) + geom_bar(mapping = aes(x = FIRARM_C, fill = AGENG_C), position = "dodge")
ggplot(data = statadata6) + geom_bar(mapping = aes(x = FIRARM_C, fill = AGENYR_C), position = "dodge")
statadata6 %>% count(DRUGS)
ggplot(data = statadata6) + stat_count(mapping = aes(x = DRUGS))
statadata7  <- arrange(statadata6, desc(YEAR), desc(AGENYR_C), desc(AGENG_C))  
View(statadata7)
statadata7 %>% count(RACE_C)
view(statadata7 %>% count(AGENYR_C))
statadata7 %>% count(AGENG_C)
ggplot(data = statadata6) + stat_count(mapping = aes(x = AGENYR_C))
statadata6 %>% count(HISP_C)
statadata9 <- statadata7 %>% filter(!is.na(MSTAT_C), !is.na(AGENYR_C)) 
View(statadata9)
View(statadata9 %>% count(AGENYR_C))
View(statadata9 %>% count(AGENG_C))
ggplot(data = statadata9) + stat_count(mapping = aes(x = AGENG_C))
View(statadata9 %>% count(ARG))
ggplot(data = statadata9) + stat_count(mapping = aes(x = ARG))
ggplot(data = statadata9) + geom_bar(mapping = aes(x = FIRARM_C, fill = ARG))
View(statadata9 %>% count(CLASS_C))
ggplot(data = statadata9) + stat_count(mapping = aes(x = CLASS_C))
ggplot(data = statadata9, mapping = aes(x = AGENYR_C, y = ..density..)) + geom_freqpoly(mapping = aes(colour = FIRARM_C), binwidth = 50)
View(statadata9 %>% count(DRUGS))
ggplot(data = statadata9) + stat_count(mapping = aes(x = DRUGS))
ggplot(data = statadata9) + geom_bar(mapping = aes(x = DRUGS, fill = ARG))
ggplot(data = statadata9) + geom_bar(mapping = aes(x = ARG, fill = DRUGS))
ggplot(data = statadata9) + geom_histogram(mapping = aes(x = AGENYR_C), binwidth = 4)
ggplot(data = statadata9) + geom_histogram(mapping = aes(x = AGENYR_C, binwidth = 10))
View(statadata9 %>% count(MSTAT_C))
ggplot(data = statadata9) + stat_count(mapping = aes(x = MSTAT_C))
View(statadata9 %>% count(CRIME))
ggplot(data = statadata9) + stat_count(mapping = aes(x = CRIME))
ggplot(data = statadata9) + geom_bar(mapping = aes(x = CRIME, fill = CRIME))
ggplot(data = statadata9) + geom_bar(mapping = aes(x = CRIME, colour = CRIME))
ggplot(data = statadata9) + geom_bar(mapping = aes(x = CRIME, fill = DRUGS))
statadata10 <- filter(statadata9,LOC_C != "Mobile home", ONTHEJOB != "Act duty military", WHO_C != "No see", WHO_C != "Other", WHO_C != "Unknown", CLASS_C != "Unknown",FIGHT != "Unknown", RACE_C != "Other", AGENG_C != "65+", MSTAT_C != "Not stated", DRUGS != "Unknown", CRIME != "Unknown", FIRARM_C != "Unknown", LOC_C != "Unknown", RACE_C != "Not stated", ONTHEJOB != "Unknown", ARG != "Unknown", DIAG != "Other", MSTAT_C != "Other")
View(statadata10)
View(statadata10 %>% count(WHO_C))
ggplot(data = statadata10) + stat_count(mapping = aes(x = WHO_C))
View(statadata10 %>% count(MSTAT_C))
ggplot(data = statadata10, mapping = aes(x = FIRARM_C, y = AGENYR_C)) + geom_boxplot()
statadata10 %>% count(RACE_C)
view(statadata10 %>% count(BDYPT))
ggplot(data = statadata10) + stat_count(mapping = aes(x = AGENYR_C))
ggplot(data = statadata9) + stat_count(mapping = aes(x = AGENG_C))
statadata10 %>% count(FIRARM_C)
ggplot(data = statadata10) + stat_count(mapping = aes(x = FIRARM_C))
statadata10 %>% count(YEAR)
View(statadata10 %>% count(YEAR))
ggplot(data = statadata10) + stat_count(mapping = aes(x = YEAR))
ggplot(data = statadata10) + stat_count(mapping = aes(x = SEX))
View(statadata10 %>% count(SEX))
statadata10 %>% count(CLASS_C)
ggplot(data = statadata10) + stat_count(mapping = aes(x = CLASS_C))
statadata10 %>% count(LOC_C)
View(statadata10 %>% count(LOC_C))
summarise(statadata10, averageage = mean(AGENYR_C))
View(statadata11 <- statadata10 %>% group_by(YEAR) %>% summarise(means = mean(AGENYR_C)))
statadata12 <- statadata10 %>% filter(between(AGENYR_C, 60, 64)) 
View(statadata12)
View(statadata12 %>% count(AGENYR_C))
ggplot(data = statadata12) + stat_count(mapping = aes(x = AGENYR_C))
ggplot(data = statadata12) + geom_bar(mapping = aes(x = AGENYR_C, fill = FIRARM_C))
View(statadata12 %>% count(RACE_C))
ggplot(data = statadata12) + stat_count(mapping = aes(x = RACE_C))
ggplot(data = statadata12) + geom_bar(mapping = aes(x = RACE_C, fill = FIRARM_C))
statadata13 <- statadata10 %>% filter(between(AGENYR_C, 15, 45)) 
View(statadata13)
View(statadata12 %>% count(ONTHEJOB))
View(statadata12 %>% count(DRUGS))
View(statadata13 %>% count(ONTHEJOB))
View(statadata13 %>% count(DRUGS))
ggplot(data = statadata13) + geom_bar(mapping = aes(x = AGENYR_C, fill = DRUGS))
statadata10 %>% ggplot(mapping = aes(AGENYR_C)) + geom_freqpoly(mapping = aes(colour = FIRARM_C), binwidth = 4)
statadata10 %>% ggplot(mapping = aes(YEAR)) + geom_freqpoly(mapping = aes(colour = AGENYR_C), binwidth = 4)
statadata12 %>% ggplot(mapping = aes(YEAR)) + geom_freqpoly(mapping = aes(colour = AGENYR_C), binwidth = 4)
statadata13 %>% ggplot(mapping = aes(YEAR)) + geom_freqpoly(mapping = aes(colour = AGENYR_C), binwidth = 4)
ggplot(data = statadata12, mapping = aes(x = FIRARM_C, y = AGENYR_C)) + geom_boxplot()
ggplot(data = statadata12, mapping = aes(x = ONTHEJOB, y = AGENYR_C)) + geom_boxplot()
ggplot(data = statadata10) + geom_count(mapping = aes(x = SEX, y = MSTAT_C))
ggplot(data = statadata10) + geom_count(mapping = aes(x = RACE_C, y = CRIME))
View(statadata10 %>% count(SEX, FIRARM_C))
statadata10 %>% count(SEX, DRUGS)
View(statadata10 %>% count(SEX, BDYPT))
View(statadata10 %>% count(DIAG, SEX))
View(statadata10 %>% count(YEAR, SEX) %>% filter(n > 25))
View(statadata10 %>% count(YEAR, FIRARM_C) %>% filter(n > 25))
statadata14 <- statadata10 %>% filter(between(YEAR, 2000, 2015)) 
View(statadata14)
statadata14 %>% count(SEX)
statadata14 %>% count(DISP)
ggplot(data = statadata14) + geom_bar(mapping = aes(x = SEX))
ggplot(data = statadata14) + geom_bar(mapping = aes(x = SEX, fill = DRUGS))
ggplot(data = statadata14) + geom_bar(mapping = aes(x = SEX, fill = CRIME))
View(statadata10 %>% count(cut_width(YEAR, 5)))
View(statadata14 %>% count(cut_width(AGENYR_C, 10)))
histo <- statadata10 %>% filter(YEAR >= 2010) 
View(histo)
ggplot(data = histo, mapping = aes(x = YEAR)) + geom_histogram(binwidth = 0.2)
ggplot(data = statadata14) + geom_bar(mapping = aes(x = SEX, fill = FIRARM_C), position = "fill")
View(statadata10 %>% count(RACE_C, AGENYR_C))
View(statadata10 %>% count(MSTAT_C, SEX ))
View(statadata10 %>% group_by(MSTAT_C, AGENG_C, SEX) %>% summarise(mean = mean(AGENYR_C, na.rm = TRUE)))
View(statadata10 %>% count(WHO_C, SEX ))
View(statadata10 %>% count(LOC_C ))
ggplot(data = statadata10) + stat_count(mapping = aes(x = LOC_C))
View(statadata10 %>% count(SEX, LOC_C ))
ggplot(data = histo) + geom_bar(mapping = aes(x = YEAR, fill = FIRARM_C), position = "fill")
ggplot(data = histo) + geom_bar(mapping = aes(x = YEAR, fill = FIRARM_C))
ggplot(data = histo) + geom_bar(mapping = aes(x = YEAR, fill = "Handgun"))
ggplot(data = histo) + geom_bar(mapping = aes(x = YEAR, fill = "Rifle"))
View(histo %>% count(YEAR))
ggplot(data = histo) + geom_bar(mapping = aes(x = YEAR, fill = FIRARM_C), position = "dodge")
ggplot(data = histo) + geom_bar(mapping = aes(x = SEX, fill = FIRARM_C), position = "dodge")
View(histo %>% count(YEAR, FIRARM_C))
View(statadata10 %>% count(YEAR, FIRARM_C))
statadata10 %>% count(HISP_C)
ggplot(data = histo) + geom_bar(mapping = aes(x = HISP_C, fill = FIRARM_C))
ggplot(data = statadata) + geom_bar(mapping = aes(x = HISP_C, fill = FIRARM_C))
ggplot(data = statadata) + geom_bar(mapping = aes(x = HISP_C, fill = FIRARM_C), position = "dodge")
ggplot(data = statadata10) + geom_bar(mapping = aes(x = ONTHEJOB, fill = FIRARM_C), position = "dodge")
View(statadata10 %>% count(SEX, ONTHEJOB))
ggplot(data = statadata10) + geom_bar(mapping = aes(x = SEX, fill = ONTHEJOB), position = "dodge")
View(histo %>% count(YEAR, CLASS_C))
View(histo2 <- statadata10 %>% filter(YEAR == 2015)) 
View(histo2 %>% count(YEAR, RACE_C))
histo2 %>% count(FIRARM_C)
ggplot(data = histo2) + stat_count(mapping = aes(x = FIRARM_C))
ggplot(data = histo2) + geom_bar(mapping = aes(x = SEX, fill = FIRARM_C), position = "fill")
View(histo2)
View(histo2 %>% count(LOC_C))
View(histo2 %>% count(MSTAT_C))
View(histo2 %>% count(SEX, MSTAT_C))
View(histo2 %>% count(AGENYR_C))
View(histo2 %>% count(AGENG_C))
View(histo2 %>% count(SEX, AGENYR_C))
View(histo2 %>% count(SEX, AGENG_C))
ggplot(data = histo2) + geom_boxplot(mapping = aes(x = FIRARM_C, y = AGENYR_C))
View(as_tibble(histo2))
View(histo2 %>% count(HISP_C))
View(histo2 %>% count(cut_width(AGENYR_C, 10)))
ggplot(data = histo2, mapping =  aes(x = MSTAT_C, y = AGENYR_C)) + geom_point()
ggplot(data = histo2) + stat_count(mapping = aes(x = MSTAT_C))
View(histo2 %>% count(ARG))
ggplot(data = histo2) + geom_histogram(mapping = aes(x = AGENYR_C), binwidth = 3)
ggplot(data = histo2, mapping = aes(x = AGENYR_C, colour = MSTAT_C)) + geom_freqpoly(binwidth = 1)
ggplot(data = histo2, mapping = aes(x = AGENYR_C, colour = MSTAT_C)) + geom_freqpoly(binwidth = 1)
View(histo3 <- statadata10 %>% filter(YEAR == 1993)) 
View(histo3 %>% count(SEX))
ggplot(data = histo3) + stat_count(mapping = aes(x = SEX))
ggplot(histo3) + geom_bar(mapping = aes(x = FIRARM_C))
View(histo3)
View(histo3 %>% count(RACE_C))
View(histo3 %>% count(LOC_C))
ggplot(data = histo3) + geom_count(mapping = aes(x = SEX, y = MSTAT_C))
ggplot(data = histo3) + geom_count(mapping = aes(x = SEX, y = RACE_C))
ggplot(data = histo3) + geom_bar(mapping = aes(x = SEX, fill = FIRARM_C), position = "fill")
ggplot(data = histo3) + geom_bar(mapping = aes(x = AGENG_C, fill = FIRARM_C), position = "fill")
View(histo3 %>% count(BDYPT))
histo3 %>% count(SEX, AGENG_C) %>% ggplot(mapping = aes(x = SEX, y = AGENG_C)) + geom_tile(mapping = aes(fill = n))
View(histo3 %>% count(CLASS_C))
ggplot(histo3) + geom_bar(mapping = aes(x =CLASS_C))
ggplot(data = histo3) + geom_bar(mapping = aes(x = CLASS_C,fill = FIRARM_C))
ggplot(data = histo3) + geom_bar(mapping = aes(x = CRIME,fill = FIRARM_C))

## chi-sq tests
View(attach(statadata10))
chisq.test(RACE_C, MSTAT_C)
chisq.test(SEX, FIRARM_C)
##Making a two way table and looking at the cell values and it is answering the question, "Is the firearm distribution different based on sex?", and the significant p-value saying that it is. Saying that there is some difference between males and females across of what firearm is involved in these events.
chisq.test(table(FIRARM_C))
##Categories have different proportions. Answering the question, "Is there one type of firearm that shows up more commonly in this data than others?" From looking at the bar charts. it is true.If the firearm proportions were all relatively similar then we would get a higher p-value. .05 is our threshold usually. If the p-value is less than .05, then we say that we reject the null hypothesis and say that the categories have significantly different proportions whereas if we get a p-value higher than .05, then we fail to reject the null hypothesis.  
chisq.test(table(AGENG_C))   
chisq.test(table(AGENYR_C)) 
chisq.test(table(YEAR)) 
chisq.test(table(DRUGS))
chisq.test(table(HISP_C))
chisq.test(table(BDYPT))
chisq.test(table(SEX))
##hypothesis that it is testing is that there is the distribution of the outcome you are looking at is the same for all levels of this categorical variable.  
chisq.test(SEX, DRUGS)
chisq.test(SEX, YEAR)
chisq.test(FIGHT, DRUGS)
chisq.test(ARG, DRUGS)
chisq.test(SEX, AGENG_C)
chisq.test(DRUGS, FIRARM_C)
chisq.test(FIRARM_C, YEAR)
chisq.test(RACE_C, YEAR)
chisq.test(RACE_C, SEX)
chisq.test(SEX, WHO_C)
chisq.test(SEX, MSTAT_C)
chisq.test(SEX, ONTHEJOB)
chisq.test(SEX, WHO_C)
chisq.test(DRUGS, CRIME)
chisq.test(SEX, LOC_C)
chisq.test(CRIME, FIGHT)
chisq.test(MSTAT_C, DRUGS)
chisq.test(DRUGS, ONTHEJOB)
chisq.test(CRIME, CLASS_C)
chisq.test(SEX, CLASS_C)
chisq.test(AGENG_C, YEAR)
chisq.test(AGENYR_C, YEAR)
chisq.test(ARG, YEAR)
chisq.test(SEX, CRIME)
chisq.test(SEX, BDYPT)
chisq.test(ARG, AGENYR_C)
chisq.test(FIGHT, YEAR)
chisq.test(ARG, SEX)
chisq.test(ARG, WHO_C)
chisq.test(RACE_C, ARG)
chisq.test(RACE_C, MSTAT_C)
chisq.test(AGENYR_C, RACE_C)
chisq.test(SEX, DISP)
chisq.test(RACE_C, DISP)
chisq.test(SEX, FIRARM_C)
chisq.test(CRIME, FIRARM_C)
chisq.test(SEX, FIGHT)
chisq.test(YEAR, DRUGS)
chisq.test(SEX, ONTHEJOB)
chisq.test(ARG, YEAR)
chisq.test(ARG, MSTAT_C)
chisq.test(YEAR, ONTHEJOB)
chisq.test(DRUGS, FIRARM_C)

View(attach(statadata12))
chisq.test(table(SEX))
chisq.test(table(DRUGS))
chisq.test(table(YEAR))
chisq.test(table(CRIME))
chisq.test(table(MSTAT_C))
chisq.test(table(FIRARM_C))
chisq.test(table(FIGHT))
chisq.test(table(AGENG_C))
chisq.test(table(AGENYR_C))
chisq.test(table(ONTHEJOB))
chisq.test(table(HISP_C))
chisq.test(table(DIAG))
chisq.test(table(RACE_C))
chisq.test(table(LOC_C))
chisq.test(YEAR, FIGHT)
chisq.test(RACE_C, ONTHEJOB)
chisq.test(table(WHO_C))
chisq.test(RACE_C, FIRARM_C)
chisq.test(SEX, FIRARM_C)




View(attach(statadata13))
chisq.test(table(AGENG_C))
chisq.test(table(AGENYR_C))
chisq.test(table(ARG))
chisq.test(table(BDYPT))
chisq.test(table(CLASS_C))
chisq.test(table(CRIME))
chisq.test(table(DIAG))
chisq.test(table(DISP))
chisq.test(table(DRUGS))
chisq.test(table(FIGHT))
chisq.test(table(FIRARM_C))
chisq.test(table(HISP_C))
chisq.test(table(LOC_C))
chisq.test(table(MSTAT_C))
chisq.test(table(ONTHEJOB))
chisq.test(table(RACE_C))
chisq.test(table(SEX))
chisq.test(table(WHO_C))
chisq.test(table(YEAR))
chisq.test(AGENG_C, ARG)
chisq.test(AGENG_C, BDYPT)
chisq.test(AGENG_C, CLASS_C)
chisq.test(AGENG_C, DRUGS)
chisq.test(AGENG_C, FIGHT)
chisq.test(AGENG_C, FIRARM_C)
chisq.test(AGENG_C, MSTAT_C)
chisq.test(AGENG_C, ONTHEJOB)
chisq.test(AGENG_C, SEX)
chisq.test(AGENG_C, YEAR)
chisq.test(AGENG_C, WHO_C)
chisq.test(AGENYR_C, ARG)
chisq.test(AGENYR_C, CLASS_C)
chisq.test(AGENYR_C, CRIME)
chisq.test(AGENYR_C, DIAG)
chisq.test(AGENYR_C, FIRARM_C)
chisq.test(AGENYR_C, YEAR)
chisq.test(AGENYR_C, SEX)
chisq.test(AGENYR_C, MSTAT_C)
chisq.test(AGENYR_C, ONTHEJOB)
chisq.test(AGENYR_C, RACE_C)           
chisq.test(AGENYR_C, FIGHT)
chisq.test(CRIME, DRUGS)
chisq.test(CRIME, FIRARM_C)
chisq.test(CRIME, ARG)
chisq.test(CRIME, YEAR)
chisq.test(CRIME, MSTAT_C)
chisq.test(CRIME, SEX)
chisq.test(CRIME, YEAR)
chisq.test(CRIME, ONTHEJOB)
chisq.test(CRIME, RACE_C)
chisq.test(CRIME, LOC_C )
chisq.test(CRIME, WHO_C)
chisq.test(DRUGS, ARG)
chisq.test(DRUGS, YEAR)
chisq.test(DRUGS, SEX)
chisq.test(DRUGS, RACE_C)
chisq.test(DRUGS, ONTHEJOB)
chisq.test(DRUGS, MSTAT_C)
chisq.test(DRUGS, LOC_C)
chisq.test(DRUGS, WHO_C)
chisq.test(RACE_C, ARG )
chisq.test(RACE_C, YEAR)
chisq.test(RACE_C, MSTAT_C)
chisq.test(RACE_C, ONTHEJOB)
chisq.test(RACE_C, SEX)
chisq.test(RACE_C, MSTAT_C)
chisq.test(RACE_C, CRIME)
chisq.test(RACE_C, FIRARM_C)
chisq.test(RACE_C, LOC_C)
chisq.test(RACE_C, WHO_C)
chisq.test(DRUGS, YEAR)
chisq.test(DRUGS, ONTHEJOB)
chisq.test(HISP_C, ONTHEJOB)
chisq.test(BDYPT, ONTHEJOB)
chisq.test(WHO_C, ONTHEJOB)
chisq.test(DRUGS, DIAG)
chisq.test(DRUGS, LOC_C)
chisq.test(SEX, FIRARM_C)
chisq.test(SEX, FIGHT)
chisq.test(DRUGS, FIGHT)
chisq.test(FIRARM_C, ONTHEJOB)
chisq.test(DRUGS, LOC_C)

##View(statadata13 %>% count(RACE_C))
ggplot(data = statadata13) + stat_count(mapping = aes(x = RACE_C))
##View(statadata13 %>% count(FIRARM_C))
ggplot(data = statadata13) + stat_count(mapping = aes(x = FIRARM_C))
##View(statadata13)
attach(statadata)
chisq.test(table(SEX))
chisq.test(table(FIRARM_C))
chisq.test(table(MSTAT_C))
chisq.test(table(DRUGS))
chisq.test(table(FIGHT))
chisq.test(table(ONTHEJOB))
chisq.test(table(DRUGS))
chisq.test(table(HISP_C))
chisq.test(table(RACE_C))
chisq.test(table(FIGHT))
chisq.test(table(CLASS_C))
chisq.test(table(AGENYR_C))
chisq.test(table(AGENG_C))
chisq.test(SEX, DRUGS)
chisq.test(SEX, FIRARM_C)
chisq.test(DRUGS, FIRARM_C)
chisq.test(FIRARM_C, ONTHEJOB)
chisq.test(SEX, MSTAT_C)
chisq.test(AGENG_C, DRUGS)
chisq.test(AGENG_C, FIRARM_C)
chisq.test(AGENYR_C, FIRARM_C)
chisq.test(SEX, FIGHT)
chisq.test(SEX, RACE_C)
chisq.test(table(CRIME))
chisq.test(SEX, CRIME)
chisq.test(DRUGS, CRIME)
chisq.test(CRIME, FIRARM_C)
chisq.test(table(DIAG))
chisq.test(SEX, DIAG)
chisq.test(RACE_C, DIAG)
chisq.test(DIAG, FIRARM_C)
chisq.test(SEX, FIRARM_C)
chisq.test(MSTAT_C, FIRARM_C)
chisq.test(MSTAT_C, DRUGS)
chisq.test(MSTAT_C, SEX)
chisq.test(table(STRATUM))
chisq.test(SEX, ONTHEJOB)
chisq.test(DRUGS, ONTHEJOB)
chisq.test(DRUGS, FIRARM_C)
chisq.test(DIAG, FIRARM_C)
chisq.test(RACE_C, FIRARM_C)
chisq.test(RACE_C, DRUGS)
chisq.test(DRUGS, AGENYR_C)
chisq.test(DRUGS, AGENG_C)
chisq.test(HISP_C, DRUGS)
chisq.test(HISP_C, RACE_C)
chisq.test(HISP_C, FIRARM_C)
chisq.test(HISP_C, AGENG_C)
chisq.test(HISP_C, MSTAT_C)
chisq.test(HISP_C, ONTHEJOB)
chisq.test(HISP_C, SEX)
chisq.test(HISP_C, BDYPT)
chisq.test(HISP_C,CRIME)
chisq.test(CRIME, ONTHEJOB)

attach(statadata9)
chisq.test(table(AGENYR_C))
chisq.test(table(FIRARM_C))
chisq.test(table(MSTAT_C))
chisq.test(table(DRUGS))
chisq.test(table(FIGHT))
chisq.test(table(AGENG_C))
chisq.test(table(SEX))
chisq.test(table(RACE_C))
chisq.test(table(HISP_C))
chisq.test(SEX, DRUGS)
chisq.test(FIRARM_C, DRUGS)




##statadata15  <- group_by(statadata10,SEX, RACE_C) 
##summarise(statadata15, averageage = mean(AGENYR_C, na.rm = TRUE))
##View(statadata16 <- group_by(statadata12, SEX, RACE_C)) 
##View(summarise(statadata16, averageage2 = mean(AGENYR_C)))
##statadata17 <- group_by(statadata, SEX, RACE_C) 
##View(summarise(statadata17, averageage3 = mean(AGENYR_C, na.rm = TRUE)))
##statadata18 <- group_by(statadata, SEX, HISP_C) 
##View(summarise(statadata18, averageage4 = mean(AGENYR_C, na.rm = TRUE)))

